[package]
name = "wasm-threads-test"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1"
js-sys = "0.3.51"
rayon = "1.1.0"
rayon-core = "1.5.0"
futures-channel-preview = "0.3.0-alpha.18"
wasm-bindgen = { version = "0.2.74", features = ['serde-serialize'] }
wasm-bindgen-futures = "0.4.24"

[dependencies.web-sys]
version = "0.3.23"
features = [
  'CanvasRenderingContext2d',
  'ErrorEvent',
  'Event',
  'ImageData',
  'Navigator',
  'Window',
  'Worker',
  'DedicatedWorkerGlobalScope',
  'MessageEvent',
  'console'
]
